title: CANISGARD
description: A Dog-Breed Fantasy Setting for 5e
baseurl: "/Canisgard"
url: "https://jalenlikes2code.github.io"

markdown: kramdown
theme: null

collections:
  world:
    output: true
    permalink: /world/:name/
  rules:
    output: true
    permalink: /rules/:name/
  houses:
    output: true
    permalink: /houses/:name/
  races:
    output: true
    permalink: /races/:name/
   

defaults:
  - scope:
      path: ""
    values:
      layout: default

