title: CANISGARD
description: A Dog-Breed Fantasy Setting for 5e
baseurl: /Canisgard
url: https://jalenlikes2code.github.io

markdown: kramdown
theme: null

collections:
  world:
    output: true
 
  rules:
    output: true
  
  houses:
    output: true
   
  races:
    output: true
   

defaults:
  - scope:
      path: ""
    values:
      layout: page

